# Generated by Django 5.1 on 2024-08-24 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_invoice_item_description_invoice_item_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='description',
        ),
        migrations.AddField(
            model_name='invoice',
            name='sender',
            field=models.CharField(choices=[('en', '\n                ZEIN MOUALLA\n                IBAN - FR47 2004 1010 1114 3315 8P03 275\n                BIC/SWIFT - PSSTFRPPNTE\n                VAT Rate - 0.0%\n                No VAT has been added to this invoice in accordance\n                with EU law\n                VAT exempt - EU Directive 2006/112/EC, Article 132, 1\n                CRKBO accredited\n                Tax Number (SIREN) : 920295805\n             '), ('fr', "\n                ZEIN MOUALLA\n                4 Rue de l'étoile du Berger\n                Bouguenais - Nantes\n                zeinmou72@gmail.com\n                +33652886958\n                SIREN : 920295805\n                IBAN - FR76 4061 8804 1000 0408 9387 149\n                BIC/SWIFT - BOUSFRPPXXX\n                VAT Rate - 0.0%\n                TVA non applicable, article 293 B du Code Général des\n                Impôts\n                VAT exempt - EU Directive 2006/112/EC, Article 132, 1\n\n            ")], default='Send to', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='to',
            field=models.CharField(default='To Whom', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_date',
            field=models.DateField(),
        ),
    ]
