# Generated by Django 5.1 on 2024-08-24 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_invoice_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='sender',
            field=models.CharField(choices=[('en', '\n            ZEIN MOUALLA\n            IBAN - FR47 2004 1010 1114 3315 8P03 275\n            BIC/SWIFT - PSSTFRPPNTE\n            VAT Rate - 0.0%\n            No VAT has been added to this invoice in accordance\n            with EU law\n            VAT exempt - EU Directive 2006/112/EC, Article 132, 1\n            CRKBO accredited\n            Tax Number (SIREN) : 920295805\n             '), ('fr', "\n            ZEIN MOUALLA\n            4 Rue de l'étoile du Berger\n            Bouguenais - Nantes\n            zeinmou72@gmail.com\n            +33652886958\n            SIREN : 920295805\n            IBAN - FR76 4061 8804 1000 0408 9387 149\n            BIC/SWIFT - BOUSFRPPXXX\n            VAT Rate - 0.0%\n            TVA non applicable, article 293 B du Code Général des\n            Impôts\n            VAT exempt - EU Directive 2006/112/EC, Article 132, 1\n\n            ")], default='\n            ZEIN MOUALLA\n            IBAN - FR47 2004 1010 1114 3315 8P03 275\n            BIC/SWIFT - PSSTFRPPNTE\n            VAT Rate - 0.0%\n            No VAT has been added to this invoice in accordance\n            with EU law\n            VAT exempt - EU Directive 2006/112/EC, Article 132, 1\n            CRKBO accredited\n            Tax Number (SIREN) : 920295805\n             ', max_length=255),
        ),
    ]
