# Generated by Django 5.1 on 2024-08-26 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_invoice_sender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='item_description',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='item_quantity',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='unit_price',
        ),
    ]
