# Generated by Django 5.1 on 2024-08-28 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_invoice_item_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='sender',
            field=models.CharField(default='\n            ZEIN MOUALLA\n            IBAN - FR47 2004 1010 1114 3315 8P03 275\n            BIC/SWIFT - PSSTFRPPNTE\n            VAT Rate - 0.0%\n            No VAT has been added to this invoice in accordance\n            with EU law\n            VAT exempt - EU Directive 2006/112/EC, Article 132, 1\n            CRKBO accredited\n            Tax Number (SIREN) : 920295805\n             ', max_length=255),
        ),
    ]
