# Generated by Django 5.1 on 2024-08-31 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_invoice_sender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='identifier',
            new_name='invoice_number',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='to',
        ),
        migrations.AddField(
            model_name='invoice',
            name='client_info',
            field=models.CharField(default='no_value', max_length=800),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='company_info',
            field=models.CharField(default='no_value', max_length=800),
            preserve_default=False,
        ),
    ]
