# version: '3.8'

# services:
#   web:
#     build: .
#     command: gunicorn app.wsgi:application --bind 0.0.0.0:8000
#     ports:
#       - "8000:8000"
#     volumes:
#       - ./static:/app/static
#     depends_on:
#       - db
#     env_file:
#       - .env
#     restart: always

#   db:
#     image: postgres:13
#     environment:
#       POSTGRES_USER: myuser
#       POSTGRES_PASSWORD: mypassword
#       POSTGRES_DB: mydb
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#     restart: always

#   nginx:
#     image: nginx:alpine
#     ports:
#       - "80:80"
#     volumes:
#       - ./nginx.conf:/etc/nginx/conf.d/default.conf
#       - ./static:/app/static
#     depends_on:
#       - web
#     restart: always

# volumes:
#   postgres_data:
version: "3.9"

services:
  web:
    build: .
    container_name: django_web
    command: gunicorn --bind 0.0.0.0:8000 django_api.wsgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"

  nginx:
    image: nginx:latest
    container_name: nginx_server
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./static:/static
    ports:
      - "80:80"
    depends_on:
      - web
